#!/usr/bin/env python3

import os
import sys
import subprocess
from pathlib import Path
from shutil import copy2

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, GLib

try:
    gi.require_version("AppIndicator3", "0.1")
    from gi.repository import AppIndicator3
    HAS_APPINDICATOR = True
except (ImportError, ValueError):
    AppIndicator3 = None
    HAS_APPINDICATOR = False


APP_ID = "gzml-visual-tools"
APP_DIR = Path(__file__).resolve().parent
PRESETS_DIR = APP_DIR / "presets"
ICON_PATH = APP_DIR / "assets" / "gzml.png"
LOCK_FILE = Path("/tmp/gzml-visual-tools.lock")

STATE_DIR = APP_DIR / ".state"
GZML_CONFIG_DIR = Path.home() / ".config/gzml-visual-tools/hypr"

GZML_ANIMATION_FILE = GZML_CONFIG_DIR / "animations.lua"
GZML_BLUR_FILE = GZML_CONFIG_DIR / "blur.lua"

ACTIVE_ANIMATION_FILE = GZML_ANIMATION_FILE
ACTIVE_BLUR_FILE = STATE_DIR / "active_blur_level"
ACTIVE_BORDER_FILE = STATE_DIR / "active_border_size"

SUPPORTED_EXTENSIONS = (".sh", ".lua")

ANIMATION_INCLUDE_LINE = 'dofile(os.getenv("HOME") .. "/.config/gzml-visual-tools/hypr/animations.lua")'
BLUR_INCLUDE_LINE = 'dofile(os.getenv("HOME") .. "/.config/gzml-visual-tools/hypr/blur.lua")'


class GZMLTray:
    def __init__(self):
        self.indicator = None
        self.status_icon = None

        self.root_menu = Gtk.Menu()
        self.animation_menu = Gtk.Menu()
        self.wallpaper_menu = Gtk.Menu()
        self.theme_menu = Gtk.Menu()
        self.tools_menu = Gtk.Menu()
        self.blur_menu = Gtk.Menu()
        self.borders_menu = Gtk.Menu()

        self.ensure_single_instance()
        self.ensure_generated_config_files()
        self.setup_tray()
        self.build_root_menu()

    def ensure_single_instance(self):
        if LOCK_FILE.exists():
            try:
                old_pid = int(LOCK_FILE.read_text().strip())
                os.kill(old_pid, 0)
                print(f"{APP_ID} already running with PID {old_pid}")
                sys.exit(0)
            except (ValueError, ProcessLookupError):
                LOCK_FILE.unlink(missing_ok=True)
        LOCK_FILE.write_text(str(os.getpid()))

    def cleanup_lock(self):
        try:
            if LOCK_FILE.exists() and LOCK_FILE.read_text().strip() == str(os.getpid()):
                LOCK_FILE.unlink(missing_ok=True)
        except Exception:
            pass

    def quit(self, *_):
        self.cleanup_lock()
        Gtk.main_quit()

    def ensure_generated_config_files(self):
        GZML_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        STATE_DIR.mkdir(parents=True, exist_ok=True)

        created_files = []

        if not GZML_ANIMATION_FILE.exists():
            GZML_ANIMATION_FILE.write_text(
                "-- Generated by GZML Visual Tools.\n"
                "-- Add this to the end of your Hyprland Lua config:\n"
                f"-- {ANIMATION_INCLUDE_LINE}\n\n"
            )
            created_files.append("animations.lua")

        if not GZML_BLUR_FILE.exists():
            self.write_blur_config(0)
            created_files.append("blur.lua")

        if created_files:
            self.notify(
                "GZML Visual Tools Setup",
                "Generated "
                + ", ".join(created_files)
                + ". Add the dofile lines from the generated files to your hyprland.lua.",
            )

    def write_blur_config(self, level: int):
        GZML_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

        if level <= 0:
            enabled = "false"
            passes = 1
        else:
            enabled = "true"
            passes = max(1, min(5, int(level)))

        GZML_BLUR_FILE.write_text(
            f"""-- Generated by GZML Visual Tools.
-- Add this to the end of your Hyprland Lua config after your normal decorations:
-- {BLUR_INCLUDE_LINE}

hl.config({{
  decoration = {{
    blur = {{
      enabled = {enabled},
      size = 2,
      passes = {passes},

      new_optimizations = true,
      xray = true,
      ignore_opacity = true,
      special = true,
      popups = true,
    }},
  }},
}})
"""
        )

    def setup_tray(self):
        icon = str(ICON_PATH) if ICON_PATH.exists() else "preferences-desktop-theme"

        if HAS_APPINDICATOR:
            self.indicator = AppIndicator3.Indicator.new(
                APP_ID,
                icon,
                AppIndicator3.IndicatorCategory.APPLICATION_STATUS,
            )
            self.indicator.set_status(AppIndicator3.IndicatorStatus.ACTIVE)
            self.indicator.set_title("GZML Visual Tools")
            self.indicator.set_menu(self.root_menu)
            return

        self.status_icon = Gtk.StatusIcon()
        self.status_icon.set_name(APP_ID)

        if ICON_PATH.exists():
            self.status_icon.set_from_file(str(ICON_PATH))
        else:
            self.status_icon.set_from_icon_name("preferences-desktop-theme")

        self.status_icon.set_visible(True)
        self.status_icon.connect("popup-menu", self.show_status_menu)
        self.status_icon.connect("activate", self.show_status_menu_left_click)

    def show_status_menu(self, icon, button=0, time=0):
        self.refresh_all_submenus()
        self.root_menu.show_all()
        self.root_menu.popup(
            None,
            None,
            Gtk.StatusIcon.position_menu,
            self.status_icon,
            button,
            time,
        )

    def show_status_menu_left_click(self, icon):
        self.show_status_menu(icon, 1, Gtk.get_current_event_time())

    def notify(self, title: str, message: str):
        subprocess.Popen(
            ["notify-send", title, message],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )

    def run_detached(self, cmd):
        subprocess.Popen(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )

    def run_shell(self, command: str):
        self.run_detached(["bash", "-lc", command])

    def pretty_name(self, path: Path) -> str:
        name = path.stem
        if len(name) >= 3 and name[:2].isdigit():
            name = name[2:].lstrip(" -_")
        return name.replace("-", " ").replace("_", " ").title()

    def same_file_contents(self, a: Path, b: Path) -> bool:
        try:
            return a.read_bytes() == b.read_bytes()
        except Exception:
            return False

    def is_active_animation(self, preset: Path) -> bool:
        return (
            preset.suffix == ".lua"
            and ACTIVE_ANIMATION_FILE.exists()
            and self.same_file_contents(preset, ACTIVE_ANIMATION_FILE)
        )

    def get_preset_files(self, folder: Path):
        folder.mkdir(parents=True, exist_ok=True)
        files = []
        for ext in SUPPORTED_EXTENSIONS:
            files.extend(folder.glob(f"*{ext}"))
        return sorted(files, key=lambda p: p.name.lower())

    def clear_menu(self, menu: Gtk.Menu):
        for child in list(menu.get_children()):
            menu.remove(child)

    def read_int_state(self, path: Path, default: int) -> int:
        try:
            return int(path.read_text().strip())
        except Exception:
            return default

    def write_int_state(self, path: Path, value: int):
        STATE_DIR.mkdir(parents=True, exist_ok=True)
        path.write_text(str(value))

    def build_root_menu(self):
        self.clear_menu(self.root_menu)

        self.root_menu.append(self.make_submenu_item("Animations", self.animation_menu))
        self.root_menu.append(self.make_submenu_item("Wallpaper Effects", self.wallpaper_menu))
        self.root_menu.append(self.make_submenu_item("Themes", self.theme_menu))
        self.root_menu.append(self.make_submenu_item("Tools", self.tools_menu))
        self.root_menu.append(self.make_submenu_item("Blur", self.blur_menu))
        self.root_menu.append(self.make_submenu_item("Borders", self.borders_menu))

        self.root_menu.append(Gtk.SeparatorMenuItem())

        injector_item = Gtk.MenuItem(label="Preset Injector")
        injector_menu = Gtk.Menu()
        injector_item.set_submenu(injector_menu)
        self.build_injector_menu(injector_menu)
        self.root_menu.append(injector_item)

        self.root_menu.append(Gtk.SeparatorMenuItem())

        about_item = Gtk.MenuItem(label="About")
        about_menu = Gtk.Menu()
        about_item.set_submenu(about_menu)
        self.build_about_menu(about_menu)
        self.root_menu.append(about_item)

        quit_item = Gtk.MenuItem(label="Quit")
        quit_item.connect("activate", self.quit)
        self.root_menu.append(quit_item)

        self.refresh_all_submenus()
        self.root_menu.show_all()

    def make_submenu_item(self, label: str, submenu: Gtk.Menu):
        item = Gtk.MenuItem(label=label)
        item.set_submenu(submenu)
        submenu.connect("show", lambda *_: self.refresh_submenu(label, submenu))
        return item

    def refresh_all_submenus(self):
        self.refresh_submenu("Animations", self.animation_menu)
        self.refresh_submenu("Wallpaper Effects", self.wallpaper_menu)
        self.refresh_submenu("Themes", self.theme_menu)
        self.refresh_submenu("Tools", self.tools_menu)
        self.refresh_submenu("Blur", self.blur_menu)
        self.refresh_submenu("Borders", self.borders_menu)

    def refresh_submenu(self, title: str, submenu: Gtk.Menu):
        if title == "Blur":
            self.refresh_blur_menu(submenu)
            return

        if title == "Borders":
            self.refresh_borders_menu(submenu)
            return

        folder_map = {
            "Animations": PRESETS_DIR / "animations",
            "Wallpaper Effects": PRESETS_DIR / "wallpaper-effects",
            "Themes": PRESETS_DIR / "themes",
            "Tools": PRESETS_DIR / "tools",
        }

        folder = folder_map[title]
        self.clear_menu(submenu)

        presets = self.get_preset_files(folder)
        radio_group = None

        if presets:
            for preset in presets:
                if title == "Animations" and preset.suffix == ".lua":
                    item = Gtk.RadioMenuItem.new_with_label_from_widget(
                        radio_group,
                        self.pretty_name(preset),
                    )

                    if radio_group is None:
                        radio_group = item

                    if self.is_active_animation(preset):
                        item.set_active(True)

                    item.connect("toggled", self.on_animation_toggled, preset)
                else:
                    item = Gtk.MenuItem(label=self.pretty_name(preset))
                    item.connect("activate", self.on_preset_clicked, preset)

                submenu.append(item)
        elif title != "Tools":
            empty = Gtk.MenuItem(label="No presets found")
            empty.set_sensitive(False)
            submenu.append(empty)

        if title == "Themes":
            if presets:
                submenu.append(Gtk.SeparatorMenuItem())
            coming_soon = Gtk.MenuItem(label="Coming Soon!")
            coming_soon.set_sensitive(False)
            submenu.append(coming_soon)

        if title == "Tools":
            self.add_tools_actions(submenu)

        submenu.show_all()

    def refresh_blur_menu(self, submenu: Gtk.Menu):
        self.clear_menu(submenu)

        active_level = self.read_int_state(ACTIVE_BLUR_FILE, 0)
        group = None

        for level in range(0, 6):
            label = "Off" if level == 0 else f"Level {level}"
            item = Gtk.RadioMenuItem.new_with_label_from_widget(group, label)

            if group is None:
                group = item

            if level == active_level:
                item.set_active(True)

            item.connect("toggled", self.on_blur_toggled, level)
            submenu.append(item)

        submenu.show_all()

    def refresh_borders_menu(self, submenu: Gtk.Menu):
        self.clear_menu(submenu)

        active_size = self.read_int_state(ACTIVE_BORDER_FILE, 2)
        group = None

        for size in range(1, 11):
            label = f"{size}px"
            item = Gtk.RadioMenuItem.new_with_label_from_widget(group, label)

            if group is None:
                group = item

            if size == active_size:
                item.set_active(True)

            item.connect("toggled", self.on_border_toggled, size)
            submenu.append(item)

        submenu.show_all()

    def add_tools_actions(self, menu: Gtk.Menu):
        menu.append(Gtk.SeparatorMenuItem())

        refresh = Gtk.MenuItem(label="Refresh Preset Menus")
        refresh.connect("activate", self.on_refresh_clicked)
        menu.append(refresh)

        reload_hyprland = Gtk.MenuItem(label="Reload Hyprland")
        reload_hyprland.connect("activate", lambda *_: self.run_detached(["hyprctl", "reload"]))
        menu.append(reload_hyprland)

        open_generated_config = Gtk.MenuItem(label="Open GZML Hypr Config Folder")
        open_generated_config.connect(
            "activate",
            lambda *_: self.run_detached(["xdg-open", str(GZML_CONFIG_DIR)]),
        )
        menu.append(open_generated_config)

    def build_about_menu(self, menu: Gtk.Menu):
        self.clear_menu(menu)

        lines = [
            "GZML 2026 v0.35",
            "Git zer0-j89",
            "GTK/AppIndicator tray &",
            "Hyprland .Lua support",
            "Preset driven visual tools",
        ]

        for line in lines:
            item = Gtk.MenuItem(label=line)
            item.set_sensitive(False)
            menu.append(item)

        menu.show_all()

    def build_injector_menu(self, menu: Gtk.Menu):
        self.clear_menu(menu)

        open_folder = Gtk.MenuItem(label="Open Presets Folder")
        open_folder.connect(
            "activate",
            lambda *_: self.run_detached(["xdg-open", str(PRESETS_DIR)]),
        )
        menu.append(open_folder)

        menu.append(Gtk.SeparatorMenuItem())

        categories = [
            ("Add Animation Preset", PRESETS_DIR / "animations"),
            ("Add Wallpaper Effect Preset", PRESETS_DIR / "wallpaper-effects"),
            ("Add Theme Preset", PRESETS_DIR / "themes"),
            ("Add Tool Preset", PRESETS_DIR / "tools"),
        ]

        for label, folder in categories:
            item = Gtk.MenuItem(label=label)
            item.connect("activate", self.inject_preset, folder)
            menu.append(item)

        menu.show_all()

    def on_animation_toggled(self, item: Gtk.RadioMenuItem, preset: Path):
        if not item.get_active():
            return
        self.apply_animation(preset)

    def on_blur_toggled(self, item: Gtk.RadioMenuItem, level: int):
        if not item.get_active():
            return
        self.apply_blur(level)

    def on_border_toggled(self, item: Gtk.RadioMenuItem, size: int):
        if not item.get_active():
            return
        self.apply_border_size(size)

    def on_preset_clicked(self, item: Gtk.MenuItem, preset: Path):
        if preset.suffix == ".sh":
            self.run_shell(f'"{preset}"')
            return

        if preset.suffix == ".lua":
            self.apply_animation(preset)
            return

        self.notify("GZML Visual Tools", f"Unsupported file: {preset.name}")

    def apply_animation(self, preset: Path):
        name = self.pretty_name(preset)

        try:
            ACTIVE_ANIMATION_FILE.parent.mkdir(parents=True, exist_ok=True)
            copy2(preset, ACTIVE_ANIMATION_FILE)

            self.notify("GZML Animations", f"{name} loaded")
            self.run_detached(["hyprctl", "reload"])

            GLib.timeout_add_seconds(
                1,
                lambda: self.run_detached(["hyprctl", "configerrors"]) or False,
            )

        except Exception as e:
            self.notify("GZML Animations", f"Failed: {e}")

    def apply_blur(self, level: int):
        try:
            self.write_blur_config(level)
            self.write_int_state(ACTIVE_BLUR_FILE, level)

            if level == 0:
                self.notify("GZML Blur", "Blur disabled")
            else:
                self.notify("GZML Blur", f"Blur level {level}")

            self.run_detached(["hyprctl", "reload"])

            GLib.timeout_add_seconds(
                1,
                lambda: self.run_detached(["hyprctl", "configerrors"]) or False,
            )

        except Exception as e:
            self.notify("GZML Blur", f"Failed: {e}")

    def apply_border_size(self, size: int):
        try:
            self.run_detached(
                [
                    "hyprctl",
                    "eval",
                    f"hl.config({{ general = {{ border_size = {size} }} }})",
                ]
            )
            self.write_int_state(ACTIVE_BORDER_FILE, size)
            self.notify("GZML Borders", f"Border size {size}px")

        except Exception as e:
            self.notify("GZML Borders", f"Failed: {e}")

    def on_refresh_clicked(self, *_):
        self.refresh_all_submenus()
        self.notify("GZML Visual Tools", "Preset menus refreshed")

    def inject_preset(self, item: Gtk.MenuItem, category_folder: Path):
        category_folder.mkdir(parents=True, exist_ok=True)

        dialog = Gtk.FileChooserDialog(
            title="Choose preset file",
            action=Gtk.FileChooserAction.OPEN,
        )

        dialog.add_buttons(
            Gtk.STOCK_CANCEL,
            Gtk.ResponseType.CANCEL,
            Gtk.STOCK_OPEN,
            Gtk.ResponseType.OK,
        )

        file_filter = Gtk.FileFilter()
        file_filter.set_name("Preset files")
        file_filter.add_pattern("*.sh")
        file_filter.add_pattern("*.lua")
        dialog.add_filter(file_filter)

        response = dialog.run()

        if response == Gtk.ResponseType.OK:
            src = Path(dialog.get_filename())
            dst = category_folder / src.name

            try:
                copy2(src, dst)

                if dst.suffix == ".sh":
                    dst.chmod(dst.stat().st_mode | 0o111)

                self.notify("GZML Preset Injector", f"Added {dst.name}")
                self.refresh_all_submenus()

            except Exception as e:
                self.notify("GZML Preset Injector", f"Failed: {e}")

        dialog.destroy()


def main():
    app = GZMLTray()

    try:
        Gtk.main()
    finally:
        app.cleanup_lock()


if __name__ == "__main__":
    main()
